[main]
# 样式表路径
style=/home/node/.config/gtklock/style.css

# 启用扩展模块（音乐控制、电源菜单、用户头像）
modules=/usr/lib/x86_64-linux-gnu/gtklock/playerctl-module.so;/usr/lib/x86_64-linux-gnu/gtklock/userinfo-module.so

# 锁屏背景图片（选择一张你喜欢的高清壁纸）
background=~/图片/wallhaven-po73kp_1920x1080.png

# 密码输入框内的提示文字
input-label-text=Enter Password...
